### ISSUE TITLE
upload vendor files for common trees

### ISSUE THREAD

**Issue by WajdiMuh** [CarbonROM/android_device_sony_msm8974-common#1]
upload vendor files for common trees because proprietary-files.txt doesnt  pull all needed files or fix proprietary-files.txt so we can get vendor ourselves

**Comment by rcstar6696** [comment]
only basic vendor files are from msm8974 devices from sony. it makes no sense to create those files as only camera is still from Sony

**Comment by Myself5** [comment]
also, repositories hosting them can be easily found using a Google search for repo name + branch name you're expecting to use...
